"""Add district to hospital

Revision ID: 4126c7be12e2
Revises: a73a4d1aafee
Create Date: 2026-04-23 17:46:30.336403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4126c7be12e2'
down_revision: Union[str, Sequence[str], None] = 'a73a4d1aafee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('district', sa.String(), nullable=True))
    op.create_index(op.f('ix_hospitals_district'), 'hospitals', ['district'], unique=False)
    
    # Backfill existing hospitals
    op.execute("""
        UPDATE hospitals SET district = 'Unknown'
        WHERE district IS NULL
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hospitals_district'), table_name='hospitals')
    op.drop_column('hospitals', 'district')
    # ### end Alembic commands ###
