"""initial schema

Revision ID: b8905846aa73
Revises: 
Create Date: 2026-03-31 05:30:13.175587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8905846aa73'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conditions')
    op.drop_table('doctors')
    op.drop_table('availability')
    op.drop_column('availabilities', 'ot_available')
    op.drop_column('availabilities', 'active_cases')
    op.alter_column('hospitals', 'specialists',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hospitals', 'specialists',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.add_column('availabilities', sa.Column('active_cases', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('availabilities', sa.Column('ot_available', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.create_table('availability',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hospital_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('beds', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('icu', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('doctors', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('equipment', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=True),
    sa.Column('accepting', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('availability_hospital_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('availability_pkey'))
    )
    op.create_table('doctors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hospital_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('speciality', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('available', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('shift', sa.VARCHAR(length=20), server_default=sa.text("'day'::character varying"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('doctors_hospital_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('doctors_pkey'))
    )
    op.create_table('conditions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('condition_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('condition_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('specialists_needed', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('equipment_needed', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('facilities_needed', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('severity_weight', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('conditions_pkey')),
    sa.UniqueConstraint('condition_name', name=op.f('conditions_condition_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
